### ISSUE TITLE
Sections example

### ISSUE THREAD

**Issue by darked89** [piazzai/arguelles#1]
Hello,

First, I am very impressed by this really well designed presentation template. 

FYI: I managed to get the ```demo.tex``` compile and produce PDF on overleaf.com by simply following the advice and uploading all the ```.sty``` files to the relevant folder/project.

I am puzzled how to organize the presentation in few sections, such as:
* preface (motto, outline)
* introduction (few slides with necessary background)
* research 
* summary

Would it be possible for you to introduce some minimal example (section_1, section_2) in ```demo.tex```?

Many thanks for your help in advance.

Darek K.

**Comment by darked89** [comment]
I have found the relevant documentation here: 

* [Beamer_Presentations:_A_Tutorial_for_Beginners](https://www.overleaf.com/learn/latex/Beamer_Presentations:_A_Tutorial_for_Beginners_(Part_1)%E2%80%94Getting_Started)

**Comment by piazzai** [comment]
Hi Darek! Glad you found the solution. Please let me know if you have any other doubts.
