### ISSUE TITLE
Using includeonlyframes and overlays without having a dark background on the first slide

### ISSUE THREAD

**Issue by Zar-rok** [piazzai/arguelles#10]
Hi,

I'm using the [`includeonlyframes`](https://distrib-coffee.ipsl.jussieu.fr/pub/mirrors/ctan/macros/latex/contrib/beamer/doc/beameruserguide.pdf#page=29) command provided by Beamer in order to modify and compile a single slide at a time.

I use overlays to progressively display the content of a slide, but the first overlay of a slide has a dark background when I'm using your theme.

I guess that the problem comes from the `if` (line 65) which should work only for the title page?

https://github.com/piazzai/arguelles/blob/2c41f94e783afe81c1353d1019e0061494ebce14/beamerinnerthemeArguelles.sty#L65-L67

I use the `frameno` option and I see that `\insertframenumber` (line 70) correctly computes the number, even when I compile a single slide only.

https://github.com/piazzai/arguelles/blob/2c41f94e783afe81c1353d1019e0061494ebce14/beamerthemeArguelles.sty#L67-L73

# Question

Is it possible to use the variable considered in `\insertframenumber`, rather than `\thipage`, to change the background color for the title page only?

**Comment by piazzai** [comment]
Hi! I have no experience with `includeonlyframes` but the solution you suggest sounds perfectly fine. Line 65 should change from `\ifnum\thepage>1\relax` to `\ifnum\theframenumber>0\relax`. I just tested it and it works well, so I committed the change.

Hopefully it fixes your problem with `includeonlyframes`. In case it doesn't, please provide a MWE so I can look into it.

Thanks!

**Comment by Zar-rok** [comment]
Hi,
It solves my problem!
Thanks for your theme :)
