### ISSUE TITLE
Dots of nav-bar appear in wrong place when using subsection

### ISSUE THREAD

**Issue by juniorxxue** [piazzai/arguelles#2]
Thanks for the nice template.

<img width="147" alt="Screenshot 2022-06-20 at 5 35 35 PM" src="https://user-images.githubusercontent.com/31076337/174572723-0d846910-9797-4d6d-a547-65b0ad15adf2.png">

<img width="220" alt="Screenshot 2022-06-20 at 5 34 50 PM" src="https://user-images.githubusercontent.com/31076337/174572563-a41710c2-a943-4105-baaf-81a4aee0cb6d.png">

I noticed the dot seems not well behaved when I use "\subsection"

Is it intended?

**Comment by piazzai** [comment]
Hi! My pleasure.

That is standard behavior for the navigation bar. As far as I know you can force them all to a single line by loading beamer with the `compress` option:

`\documentclass[compress]{beamer}`

I strongly recommend it. Putting them on multiple lines is a terrible waste of space.

**Comment by piazzai** [comment]
Hi! My pleasure.

That is standard behavior for the beamer navigation bar. Default themes adapt the layout to accommodate multiple lines of dots, but this theme is built with the assumption that you keep them on a single line. Space is valuable.

You can force all of them to a single line by loading beamer with the compress option:

`\documentclass[compress]{beamer}`
