### ISSUE TITLE
Feat Request: Page Number

### ISSUE THREAD

**Issue by juniorxxue** [piazzai/arguelles#3]
Hi, it's me again.

Thanks for your template, and I basically use it in a daily basis. I have a personal request:

Do you consider the inclusion of page numbers? (maybe set it as an option)

Since in a talk, audience often wants to point out which page is related ...

I have a workable code, but it's not the perfect. Just put it before the begin{document}

```
% page number

\addtobeamertemplate{navigation symbols}{}{ \usebeamerfont{footline}%
    \large{\insertframenumber} \hspace{0.5em} \vspace{0.5em}}
```

It looks like:

<img width="825" alt="Screenshot 2023-01-30 at 4 11 12 PM" src="https://user-images.githubusercontent.com/31076337/215422372-341098bb-14ec-45b0-a4da-5f04962f065c.png">

Known issues:

It counts from and is shown in the beginning title page.

Thanks for your time.
Xu Xue

**Comment by piazzai** [comment]
Hi! Happy to know the theme is serving you well.
You can now load page numbers with the `frameno` option. The count starts after the title page.

`\usetheme[frameno]{Arguelles}`

Let me know if this is what you needed.

**Comment by juniorxxue** [comment]
wow, many thanks for your work! I tried and it's great.
